module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    ABDAR: "ABDAR",
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_CATEGORY: "ADD_PRODUCT_CATEGORY",
    ADD_SIZE: "ADD_SIZE",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },
  CONFIRMATION_MODAL_CLOSE_TYPES: {
    ROLE_DELETE: "ROLE_DELETE",
    BRAND_TYPE_DELETE: "BRAND_TYPE_DELETE",
    BRAND_DELETE: "BRAND_DELETE",
    PRODUCT_DELETE: "PRODUCT_DELETE",
    PRODUCT_CATEGORY_DELETE: "PRODUCT_CATEGORY_DELETE",
    PRODUCT_SIZE_DELETE: "PRODUCT_SIZE_DELETE",

  },
});
